package club.banyuan.machine;

public enum FlowStatus {
  ROOT,
  READ_PRODUCT_INFO,
  INSERT_COIN,
  PRESS_PRODUCT_BTN,
  PRESS_RETURN_BTN,
  SERVICE_MENU_OPEN,
  SERVICE_INSPECT_STATUS,
  SERVICE_WITHDRAW_MONEY,
  SERVICE_REFILL_PRODUCT,
  SERVICE_CHANGE_PRODUCT,
  QUIT
}
